version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo 'GENERATE_SOURCEMAP=false' >> env.production.local
      - echo "REACT_APP_API_BASE_URL=$API_ENDPOINT" >> env.production.local
      - npm install --production
  build:
    commands:
      - npm run build
      - CI=true npm run test
      - aws s3 sync build s3://$WEBSITE_BUCKET --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: build